# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  categories = Category.create([{name: 'Tech'}, {name: 'Cities'}])
  entities = Entity.create([
    {name: 'Uber', category_id: categories[0].id}, 
    {name: 'Lyft', category_id: categories[0].id}, 
    {name: "DropBox", category_id: categories[0].id}, 
    {name: "Airbnb", category_id: categories[0].id}, 
    {name: "Facebook", category_id: categories[0].id}, 
    {name: "Pinterest", category_id: categories[0].id}, 
    {name: "Salesforce.com", category_id: categories[0].id}, 
    {name: "Twitter", category_id: categories[0].id}, 
    {name: "Oracle", category_id: categories[0].id}, 
    {name: "Google", category_id: categories[0].id}, 
    {name: "Snapchat", category_id: categories[0].id}, 
    {name: "Microsoft", category_id: categories[0].id}, 
    {name: "Apple", category_id: categories[0].id}, 

    {name: 'San Francisco', category_id: categories[1].id}, 
    {name: 'New York', category_id: categories[1].id}, 
    {name: 'Portland', category_id: categories[1].id}, 
    {name: 'Austin', category_id: categories[1].id}, 
    {name: 'San Jose', category_id: categories[1].id}, 
    {name: 'Los Angeles', category_id: categories[1].id}, 
    {name: 'Philadelphia', category_id: categories[1].id}, 
    {name: 'Washington DC', category_id: categories[1].id}, 
    {name: 'Detroit', category_id: categories[1].id}, 
    {name: 'Chicago', category_id: categories[1].id}, 
    {name: 'Kansas City', category_id: categories[1].id}, 
    {name: 'Atlanta', category_id: categories[1].id}, 
    {name: 'Miami', category_id: categories[1].id}
    ])

  scales = Scale.create([
    {name: 'Expected Success', positive: 'Game Changer', negative: 'Cautionary Tale', category_id: categories[0].id}, 
    {name: 'Usefulness', positive: 'Crucial', negative: 'Useless', category_id: categories[0].id},
    {name: 'Design', positive: 'Slick', negative: 'Painful', category_id: categories[0].id},
    {name: 'Innovation', positive: 'The Future', negative: 'Treading Water', category_id: categories[0].id},
    {name: 'Social Impact', positive: 'Improves Society', negative: 'Devolution', category_id: categories[0].id},
    {name: 'Employee Perks', positive: 'Open Handed', negative: 'Tight Fisted', category_id: categories[0].id},

    {name: 'Cost of Living', positive: 'Cheap', negative: 'Expen$ive', category_id: categories[1].id},
    {name: 'Health', positive: 'Marathon Runners', negative: 'Couch Dwellers', category_id: categories[1].id},
    {name: 'Governance', positive: 'Serves the people', negative: 'Basket Case', category_id: categories[1].id},
    {name: 'Culture', positive: 'Supports the Arts', negative: 'Wasteland', category_id: categories[1].id},
    {name: 'Traffic', positive: 'Open Roads', negative: 'Gridlock', category_id: categories[1].id},
    {name: 'Economy', positive: 'Boomtown', negative: 'Ghostown', category_id: categories[1].id},
    {name: 'Resident Sexiness', positive: 'Channing Tatum', negative: 'Hugh Hefner', category_id: categories[1].id}
    ])
  joins = EntitiesScale.create([{entity_id: entities[0].id, scale_id: scales[0].id, score: 9, total: 10},
    {entity_id: entities[0].id, scale_id: scales[1].id, score: 7, total: 10},
    {entity_id: entities[0].id, scale_id: scales[2].id, score: 2, total: 10},
    {entity_id: entities[0].id, scale_id: scales[3].id, score: 7, total: 10},
    {entity_id: entities[0].id, scale_id: scales[4].id, score: -5, total: 10},
    {entity_id: entities[0].id, scale_id: scales[5].id, score: 4, total: 10},

    {entity_id: entities[1].id, scale_id: scales[0].id, score: 4, total: 10},
    {entity_id: entities[1].id, scale_id: scales[1].id, score: 7, total: 10},
    {entity_id: entities[1].id, scale_id: scales[2].id, score: 8, total: 10},
    {entity_id: entities[1].id, scale_id: scales[3].id, score: 1, total: 10},
    {entity_id: entities[1].id, scale_id: scales[4].id, score: 1, total: 10},
    {entity_id: entities[1].id, scale_id: scales[5].id, score: -3, total: 10},

    {entity_id: entities[2].id, scale_id: scales[0].id, score: 4, total: 10},
    {entity_id: entities[2].id, scale_id: scales[1].id, score: 8, total: 10},
    {entity_id: entities[2].id, scale_id: scales[2].id, score: -2, total: 10},
    {entity_id: entities[2].id, scale_id: scales[3].id, score: 6, total: 10},
    {entity_id: entities[2].id, scale_id: scales[4].id, score: 0, total: 10},
    {entity_id: entities[2].id, scale_id: scales[5].id, score: 3, total: 10},

    {entity_id: entities[3].id, scale_id: scales[0].id, score: 6, total: 10},
    {entity_id: entities[3].id, scale_id: scales[1].id, score: 9, total: 10},
    {entity_id: entities[3].id, scale_id: scales[2].id, score: -5, total: 10},
    {entity_id: entities[3].id, scale_id: scales[3].id, score: 4, total: 10},
    {entity_id: entities[3].id, scale_id: scales[4].id, score: -3, total: 10},
    {entity_id: entities[3].id, scale_id: scales[5].id, score: 9, total: 10},

    {entity_id: entities[4].id, scale_id: scales[0].id, score: 10, total: 10},
    {entity_id: entities[4].id, scale_id: scales[1].id, score: 5, total: 10},
    {entity_id: entities[4].id, scale_id: scales[2].id, score: -8, total: 10},
    {entity_id: entities[4].id, scale_id: scales[3].id, score: 6, total: 10},
    {entity_id: entities[4].id, scale_id: scales[4].id, score: -5, total: 10},
    {entity_id: entities[4].id, scale_id: scales[5].id, score: 7, total: 10},

    {entity_id: entities[5].id, scale_id: scales[0].id, score: 7, total: 10},
    {entity_id: entities[5].id, scale_id: scales[1].id, score: 3, total: 10},
    {entity_id: entities[5].id, scale_id: scales[2].id, score: 10, total: 10},
    {entity_id: entities[5].id, scale_id: scales[3].id, score: -5, total: 10},
    {entity_id: entities[5].id, scale_id: scales[4].id, score: 3, total: 10},
    {entity_id: entities[5].id, scale_id: scales[5].id, score: 7, total: 10},

   {entity_id: entities[6].id, scale_id: scales[0].id, score: 7, total: 10},
   {entity_id: entities[6].id, scale_id: scales[1].id, score: 8, total: 10},
   {entity_id: entities[6].id, scale_id: scales[2].id, score: -2, total: 10},
   {entity_id: entities[6].id, scale_id: scales[3].id, score: 7, total: 10},
   {entity_id: entities[6].id, scale_id: scales[4].id, score: -4, total: 10},
   {entity_id: entities[6].id, scale_id: scales[5].id, score: -5, total: 10},

   {entity_id: entities[7].id, scale_id: scales[0].id, score: 3, total: 10},
   {entity_id: entities[7].id, scale_id: scales[1].id, score: -5, total: 10},
   {entity_id: entities[7].id, scale_id: scales[2].id, score: -2, total: 10},
   {entity_id: entities[7].id, scale_id: scales[3].id, score: 3, total: 10},
   {entity_id: entities[7].id, scale_id: scales[4].id, score: -5, total: 10},
   {entity_id: entities[7].id, scale_id: scales[5].id, score: 3, total: 10},

   {entity_id: entities[8].id, scale_id: scales[0].id, score: 9, total: 10},
   {entity_id: entities[8].id, scale_id: scales[1].id, score: -2, total: 10},
   {entity_id: entities[8].id, scale_id: scales[2].id, score: -6, total: 10},
   {entity_id: entities[8].id, scale_id: scales[3].id, score: -8, total: 10},
   {entity_id: entities[8].id, scale_id: scales[4].id, score: -8, total: 10},
   {entity_id: entities[8].id, scale_id: scales[5].id, score: -3, total: 10},

   {entity_id: entities[9].id, scale_id: scales[0].id, score: 10, total: 10},
   {entity_id: entities[9].id, scale_id: scales[1].id, score: 9, total: 10},
   {entity_id: entities[9].id, scale_id: scales[2].id, score: -5, total: 10},
   {entity_id: entities[9].id, scale_id: scales[3].id, score: 9, total: 10},
   {entity_id: entities[9].id, scale_id: scales[4].id, score: 9, total: 10},
   {entity_id: entities[9].id, scale_id: scales[5].id, score: 3, total: 10},

   {entity_id: entities[10].id, scale_id: scales[0].id, score: 3, total: 10},
   {entity_id: entities[10].id, scale_id: scales[1].id, score: -8, total: 10},
   {entity_id: entities[10].id, scale_id: scales[2].id, score: -4, total: 10},
   {entity_id: entities[10].id, scale_id: scales[3].id, score: 5, total: 10},
   {entity_id: entities[10].id, scale_id: scales[4].id, score: -4, total: 10},
   {entity_id: entities[10].id, scale_id: scales[5].id, score: 3, total: 10},

   {entity_id: entities[11].id, scale_id: scales[0].id, score: 8, total: 10},
   {entity_id: entities[11].id, scale_id: scales[1].id, score: -4, total: 10},
   {entity_id: entities[11].id, scale_id: scales[2].id, score: -8, total: 10},
   {entity_id: entities[11].id, scale_id: scales[3].id, score: -3, total: 10},
    {entity_id: entities[11].id, scale_id: scales[4].id, score: 6, total: 10},
   {entity_id: entities[11].id, scale_id: scales[5].id, score: -6, total: 10},

   {entity_id: entities[12].id, scale_id: scales[0].id, score: 7, total: 10},
   {entity_id: entities[12].id, scale_id: scales[1].id, score: 7, total: 10},
   {entity_id: entities[12].id, scale_id: scales[2].id, score: 9, total: 10},
   {entity_id: entities[12].id, scale_id: scales[3].id, score: 8, total: 10},
   {entity_id: entities[12].id, scale_id: scales[4].id, score: -6, total: 10},
   {entity_id: entities[12].id, scale_id: scales[5].id, score: -6, total: 10},
#START OF CITIES
   {entity_id: entities[13].id, scale_id: scales[6].id, score: -9, total: 10},
   {entity_id: entities[13].id, scale_id: scales[7].id, score: 6, total: 10},
   {entity_id: entities[13].id, scale_id: scales[8].id, score: -2, total: 10},
   {entity_id: entities[13].id, scale_id: scales[9].id, score: 6, total: 10},   
   {entity_id: entities[13].id, scale_id: scales[10].id, score: -6, total: 10},
   {entity_id: entities[13].id, scale_id: scales[11].id, score: 9, total: 10},
   {entity_id: entities[13].id, scale_id: scales[12].id, score: 2, total: 10},

   {entity_id: entities[14].id, scale_id: scales[6].id, score: -7, total: 10},
   {entity_id: entities[14].id, scale_id: scales[7].id, score: 3, total: 10},
   {entity_id: entities[14].id, scale_id: scales[8].id, score: 4, total: 10},
   {entity_id: entities[14].id, scale_id: scales[9].id, score: 9, total: 10},
   {entity_id: entities[14].id, scale_id: scales[10].id, score: -9, total: 10},
   {entity_id: entities[14].id, scale_id: scales[11].id, score: 8, total: 10},
   {entity_id: entities[14].id, scale_id: scales[12].id, score: 7, total: 10},

   {entity_id: entities[15].id, scale_id: scales[6].id, score: 3, total: 10},
   {entity_id: entities[15].id, scale_id: scales[7].id, score: 9, total: 10},
   {entity_id: entities[15].id, scale_id: scales[8].id, score: 7, total: 10},
   {entity_id: entities[15].id, scale_id: scales[9].id, score: 3, total: 10},
   {entity_id: entities[15].id, scale_id: scales[10].id, score: -3, total: 10},
   {entity_id: entities[15].id, scale_id: scales[11].id, score: 7, total: 10},
   {entity_id: entities[15].id, scale_id: scales[12].id, score: 3, total: 10},

   {entity_id: entities[16].id, scale_id: scales[6].id, score: 2, total: 10},
   {entity_id: entities[16].id, scale_id: scales[7].id, score: 6, total: 10},
   {entity_id: entities[16].id, scale_id: scales[8].id, score: 9, total: 10},      
   {entity_id: entities[16].id, scale_id: scales[9].id, score: -5, total: 10},
   {entity_id: entities[16].id, scale_id: scales[10].id, score: -5, total: 10},
   {entity_id: entities[16].id, scale_id: scales[11].id, score: 8, total: 10},
   {entity_id: entities[16].id, scale_id: scales[12].id, score: 9, total: 10},

   {entity_id: entities[17].id, scale_id: scales[6].id, score: -5, total: 10},
   {entity_id: entities[17].id, scale_id: scales[7].id, score: 6, total: 10},
   {entity_id: entities[17].id, scale_id: scales[8].id, score: 6, total: 10},      
   {entity_id: entities[17].id, scale_id: scales[9].id, score: -8, total: 10},
   {entity_id: entities[17].id, scale_id: scales[10].id, score: -6, total: 10},
   {entity_id: entities[17].id, scale_id: scales[11].id, score: 8, total: 10},
   {entity_id: entities[17].id, scale_id: scales[12].id, score: 3, total: 10},

   {entity_id: entities[18].id, scale_id: scales[6].id, score: -5, total: 10},
   {entity_id: entities[18].id, scale_id: scales[7].id, score: -5, total: 10},
   {entity_id: entities[18].id, scale_id: scales[8].id, score: 2, total: 10},      
   {entity_id: entities[18].id, scale_id: scales[9].id, score: 5, total: 10},
   {entity_id: entities[18].id, scale_id: scales[10].id, score: -10, total: 10},
   {entity_id: entities[18].id, scale_id: scales[11].id, score: 4, total: 10},
   {entity_id: entities[18].id, scale_id: scales[12].id, score: 10, total: 10},

   {entity_id: entities[19].id, scale_id: scales[6].id, score: -2, total: 10},
   {entity_id: entities[19].id, scale_id: scales[7].id, score: -8, total: 10},
   {entity_id: entities[19].id, scale_id: scales[8].id, score: -5, total: 10},      
   {entity_id: entities[19].id, scale_id: scales[9].id, score: -5, total: 10},
   {entity_id: entities[19].id, scale_id: scales[10].id, score: -6, total: 10},
   {entity_id: entities[19].id, scale_id: scales[11].id, score: -4, total: 10},
   {entity_id: entities[19].id, scale_id: scales[12].id, score: -8, total: 10},

   {entity_id: entities[20].id, scale_id: scales[6].id, score: -5, total: 10},
   {entity_id: entities[20].id, scale_id: scales[7].id, score: -5, total: 10},
   {entity_id: entities[20].id, scale_id: scales[8].id, score: -10, total: 10},      
   {entity_id: entities[20].id, scale_id: scales[9].id, score: -7, total: 10},
   {entity_id: entities[20].id, scale_id: scales[10].id, score: -7, total: 10},
   {entity_id: entities[20].id, scale_id: scales[11].id, score: 7, total: 10},
   {entity_id: entities[20].id, scale_id: scales[12].id, score: -8, total: 10},

   {entity_id: entities[21].id, scale_id: scales[6].id, score: 9, total: 10},
   {entity_id: entities[21].id, scale_id: scales[7].id, score: -9, total: 10},
   {entity_id: entities[21].id, scale_id: scales[8].id, score: -10, total: 10},      
   {entity_id: entities[21].id, scale_id: scales[9].id, score: -3, total: 10},
   {entity_id: entities[21].id, scale_id: scales[10].id, score: 5, total: 10},
   {entity_id: entities[21].id, scale_id: scales[11].id, score: -9, total: 10},
   {entity_id: entities[21].id, scale_id: scales[12].id, score: 5, total: 10},

   {entity_id: entities[22].id, scale_id: scales[6].id, score: 4, total: 10},
   {entity_id: entities[22].id, scale_id: scales[7].id, score: -6, total: 10},
   {entity_id: entities[22].id, scale_id: scales[8].id, score: -6, total: 10},      
   {entity_id: entities[22].id, scale_id: scales[9].id, score: -3, total: 10},
   {entity_id: entities[22].id, scale_id: scales[10].id, score: -5, total: 10},
   {entity_id: entities[22].id, scale_id: scales[11].id, score: -2, total: 10},
   {entity_id: entities[22].id, scale_id: scales[12].id, score: -2, total: 10},

   {entity_id: entities[23].id, scale_id: scales[6].id, score: 9, total: 10},
   {entity_id: entities[23].id, scale_id: scales[7].id, score: -4, total: 10},
   {entity_id: entities[23].id, scale_id: scales[8].id, score: 4, total: 10},      
   {entity_id: entities[23].id, scale_id: scales[9].id, score: -7, total: 10},
   {entity_id: entities[23].id, scale_id: scales[10].id, score: 2, total: 10},
   {entity_id: entities[23].id, scale_id: scales[11].id, score: 4, total: 10},
   {entity_id: entities[23].id, scale_id: scales[12].id, score: 6, total: 10},

   {entity_id: entities[24].id, scale_id: scales[6].id, score: 7, total: 10},
   {entity_id: entities[24].id, scale_id: scales[7].id, score: -7, total: 10},
   {entity_id: entities[24].id, scale_id: scales[8].id, score: 6, total: 10},      
   {entity_id: entities[24].id, scale_id: scales[9].id, score: 6, total: 10},
   {entity_id: entities[24].id, scale_id: scales[10].id, score: -5, total: 10},
   {entity_id: entities[24].id, scale_id: scales[11].id, score: 4, total: 10},
   {entity_id: entities[24].id, scale_id: scales[12].id, score: 8, total: 10},

   {entity_id: entities[25].id, scale_id: scales[6].id, score: 3, total: 10},
   {entity_id: entities[25].id, scale_id: scales[7].id, score: 3, total: 10},
   {entity_id: entities[25].id, scale_id: scales[8].id, score: -5, total: 10},      
   {entity_id: entities[25].id, scale_id: scales[9].id, score: -7, total: 10},
   {entity_id: entities[25].id, scale_id: scales[10].id, score: -9, total: 10},
   {entity_id: entities[25].id, scale_id: scales[11].id, score: 4, total: 10},
   {entity_id: entities[25].id, scale_id: scales[12].id, score: 8, total: 10}   


       ])